name: "+ Update aqua user list"
on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  update-list:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: 1.21.4

      - id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{secrets.APP_ID_AQUAPROJ_AQUA}}
          private_key: ${{secrets.APP_PRIVATE_KEY_AQUAPROJ_AQUA}}

      - uses: aquaproj/aqua-installer@fd2089d1f56724d6456f24d58605e6964deae124 # v2.3.2
        # Install ghcp
        with:
          aqua_version: v2.27.3
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - run: ghcp -v
        env:
          GITHUB_TOKEN: ${{github.token}}

      - run: go run ./cmd/list-aqua-users | tee docs/LIST.md
        env:
          GITHUB_TOKEN: ${{github.token}}
      - run: cat docs/HEADER.md docs/LIST.md docs/FOOTER.md > README.md
      - id: create-branch
        run: |
          branch=update-list-$(date +%Y%m%d%H%M%S)
          echo "branch=$branch" >> "$GITHUB_OUTPUT"
          ghcp commit -r "$GITHUB_REPOSITORY" -m "docs: update the user list" -b "$branch" README.md docs/LIST.md
        env:
          GITHUB_TOKEN: ${{steps.generate_token.outputs.token}}
      - run: |
          body="This pull request is created by [GitHub Actions]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID)."
          gh pr create -t "docs: update the user list" -H "$BRANCH" -b "$body"
        env:
          BRANCH: ${{steps.create-branch.outputs.branch}}
          GITHUB_TOKEN: ${{steps.generate_token.outputs.token}}
