---
name: ghalint
on: workflow_call
env:
  AQUA_LOG_COLOR: always
jobs:
  ghalint:
    # Validate GitHub Actions Workflows by ghalint.
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - uses: aquaproj/aqua-installer@fd2089d1f56724d6456f24d58605e6964deae124 # v2.3.2
        with:
          aqua_version: v2.27.3
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - run: ghalint run
        env:
          GHALINT_LOG_COLOR: always
          AQUA_GITHUB_TOKEN: ${{github.token}}
