---
name: test
on: workflow_call

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: 1.21.4
          cache: true
      - uses: aquaproj/aqua-installer@fd2089d1f56724d6456f24d58605e6964deae124 # v2.3.2
        with:
          aqua_version: v2.27.1
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - run: golangci-lint run --timeout 120s
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - run: go test -v ./... -race -covermode=atomic
